import type { Metadata } from 'next'

import './globals.css'
import { Playfair_Display, Source_Sans_3 } from 'next/font/google'

const fontSans = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
})

const fontMono = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark' suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                document.documentElement.classList.add('dark');
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased bg-black text-white`}
      >
        {children}
      </body>
    </html>
  )
}
