import type { Metadata } from 'next'

import './globals.css'
import { Playfair_Display, Source_Sans_3 } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'

import { Spotlight } from '@/components/ui/spotlight-new'

const fontSans = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
})

const fontMono = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark' suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased bg-black text-white`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
